[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Disaster Management: Investigating the Role of Intelligent Technologies in Responding to Natural Disasters"
